### ISSUE TITLE
Flink Samples do not work in Pravega 0.6

### ISSUE THREAD

**Issue by RaulGracia** [pravega/flink-connectors#337]
**Problem description**
I was going to execute the Flink wordcount sample, and it turns out that the compiled wordcount reader and writer are crashing:
```
pravega-samples/flink-connector-examples/build/install/pravega-flink-examples$ bin/wordCountWriter
Exception in thread "main" java.lang.NoSuchMethodError: io.pravega.shared.controller.tracing.RPCTracingHelpers.getClientInterceptor()Lio/grpc/ClientInterceptor;
	at io.pravega.client.stream.impl.ControllerImpl.<init>(ControllerImpl.java:183)
	at io.pravega.client.stream.impl.ControllerImpl.<init>(ControllerImpl.java:142)
	at io.pravega.client.admin.impl.StreamManagerImpl.<init>(StreamManagerImpl.java:49)
	at io.pravega.client.admin.StreamManager.create(StreamManager.java:42)
	at io.pravega.example.flink.Utils.createStream(Utils.java:41)
	at io.pravega.example.flink.Utils.createStream(Utils.java:27)
	at io.pravega.example.flink.wordcount.WordCountWriter.main(WordCountWriter.java:62)
```
Looks like the library used is wrong in the Flink connector, given that the regular Pravega samples work well.

**Problem location**
Flink connector from 0.6.0 to 0.6.2.

**Suggestions for an improvement**
Fix why the Flink connector cannot be used after regular compilation.

**Comment by crazyzhou** [comment]
This bug is caused by the relocation of the `io.grpc` package. The return structure of the `getClientInterceptor` in flink connector is changed to `io.pravega.shaded.io.grpc` rather than `io.grpc`, causing the `io.grpc` return method not exist. See:
 https://github.com/pravega/flink-connectors/blob/master/build.gradle#L157
It's a behaviour from the _first_ commit of the repository. It was meant to shade the common libraries which could cause potential version conflicts with Flink.

**Comment by RaulGracia** [comment]
Thanks @crazyzhou , will then close this PR and open it on the samples repo.
